version: '3'
services:
  selenium:
    image: selenium/standalone-chrome:119.0
    ports:
      - "4444:4444"

  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SUPPLIER_EMAIL="shawn@jeffspoolspa.com"
      - SUPPLIER_PASSWORD="Swimmin01"
    depends_on:
      - selenium
